name: PHP8.3

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.3
        with:
          dir: "."
